version: "3"
services:
  nodejs:
    build:
      context: ./nodejs # Dockerfile保存場所
      dockerfile: Dockerfile # Dockerfileファイル名
    image: muzudho/outfield-kifuwarabe-web # イメージ名
    container_name: outfield-kifuwarabe-web # コンテナ名
    ports: # ポート接続
      - 49160:8080
      # - 80:8080 # 本番環境では
